/* Automatically generated by chibi-ffi; version: 0.5 */

#include <chibi/eval.h>

#include "stdio.h"

#include "stdbool.h"

#include "stdlib.h"

#include "stdio.h"

#include "unistd.h"


/*
types: ()
enums: ()
*/

sexp sexp_timer_init_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = ((timer_init()), SEXP_VOID);
  return res;
}

sexp sexp_set_timer_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1) {
  sexp res;
  if (! sexp_exact_integerp(arg0))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg0);
  res = sexp_make_integer(ctx, set_timer(sexp_sint_value(arg0), sexp_truep(arg1)));
  return res;
}


sexp sexp_init_library (sexp ctx, sexp self, sexp_sint_t n, sexp env, const char* version, const sexp_abi_identifier_t abi) {
  sexp_gc_var3(name, tmp, op);
  if (!(sexp_version_compatible(ctx, version, sexp_version)
        && sexp_abi_compatible(ctx, abi, SEXP_ABI_IDENTIFIER)))
    return SEXP_ABI_ERROR;
  sexp_gc_preserve3(ctx, name, tmp, op);
  op = sexp_define_foreign(ctx, env, "timer_init", 0, (sexp_proc1)sexp_timer_init_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
  }
  op = sexp_define_foreign(ctx, env, "set_timer", 2, (sexp_proc1)sexp_set_timer_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
  }
  sexp_gc_release3(ctx);
  return SEXP_VOID;
}

